config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'home#index'
  resources :groups do
    member do
      get 'members'
      post 'add_members'
      get 'make_audit'
    end
    resources :group_transactions
    resources :group_audits, only: [:index, :show]
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_members
  has_many :group_transactions
  has_many :group_audits

  validates :name, uniqueness: { scope: :user_id,
    message: "should happen once per user" }

  after_create :add_admin

  def add_members(members)
    members.each do |mem|
      self.group_members.find_or_create_by({user_id: mem}).save
    end
    
  end

  def add_admin
    self.group_members.find_or_create_by({user_id: self.user_id, accepted: true, is_admin: true}).save
  end

  def make_audit(user_id)
    last_audit = self.group_audits.last.try(:created_at)
    
    members = self.group_members.collect{|gm| {gm.user_id => 0}}.reduce Hash.new, :merge
    members_size = members.size
    group_transactions  = self.group_transactions
    group_transactions = group_transactions.where("created_at > ?", last_audit) if last_audit.present?
    group_transactions.each do |gt|
      next if gt.amount < 1
      if gt.all_group
        amount = (gt.amount / members_size)
        my_amt = ((gt.amount / members_size) * (members_size - 1))
        members.each do |key, value|
          if key == gt.user_id
            members[key] = value + my_amt
          else
            members[key] = value - amount
          end
        end
      else
        if gt.group_transaction_members_count > 1
          amount = gt.amount / (gt.group_transaction_members_count)
          my_amt = (gt.amount / (gt.group_transaction_members_count)) * (gt.group_transaction_members_count - 1)
          gt.group_transaction_members.each do |gtm|
            if gtm.user_id == gt.user_id
              members[gtm.user_id] = members[gtm.user_id] + my_amt
            else
              members[gtm.user_id] = members[gtm.user_id] - amount
            end
          end
        else
          members[gt.user_id] = members[gt.user_id] + gt.amount 
        end
      end
      
    end
    
    self.group_audits.new({user_id: user_id, report: members.to_s}).save
    members.each do |key, value|
      self.group_members.where(user_id: key).update_all({balance: value})
    end
  end
end

app/models/group_audit.rb
class GroupAudit < ActiveRecord::Base

  belongs_to :group
  belongs_to :user

  def au_report 
    members = eval(self.report)
    users = []
    return users if members.nil?
    members.each do |key, value|
      users << {User.where(id: key).last.try(:email) => value }
    end
    return users
  end
  
end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/group_transaction.rb
class GroupTransaction < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
  has_many :group_transaction_members
  
  attr_accessor :members
  
  def add_members(members)
    members.each do |key, value|
      self.group_transaction_members.find_or_create_by({group_member_id: key, user_id: value}).save
    end
  end
end

app/models/group_transaction_member.rb
class GroupTransactionMember < ActiveRecord::Base
  belongs_to :group_transaction, :counter_cache => true
  belongs_to :group_member
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
  has_many :group_members
  has_many :my_groups, through: :group_members, source: :group
  
  validates :mobile,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10, :maximum => 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource) 
    "/groups"
  end 
  
  def after_sign_up_path_for(resource) 
    "/groups"
  end 

  protected

  def configure_permitted_parameters
    # Fields for sign up
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :mobile) }
    # Fields for editing an existing account
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password) }
  end
end

app/controllers/group_audits_controller.rb
class GroupAuditsController < ApplicationController

  def index
    @group  = current_user.groups.where(id: params[:group_id]).first
    
    if @group
      @group_audits = @group.group_audits
    else
      redirect_to "/groups"
    end
  end

  def show
    @group  = current_user.groups.where(id: params[:group_id]).first
    
    if @group
      @group_audit = @group.group_audits.where(id: params[:id]).first
      @users = @group_audit.au_report 
      
      previous_audit =  @group.group_audits.where("id < ? ", @group_audit.id).last
      @transaction = @group.group_transactions.where("created_at <= ?", @group_audit.created_at)
      if previous_audit.present?
        @transaction = @transaction.where("created_at  >= ?", previous_audit.created_at)
      end
      #@group_audits = @group.group_audits
    else
      redirect_to "/groups"
    end
  end
  
end

app/controllers/group_transactions_controller.rb
class GroupTransactionsController < ApplicationController
  def index
    
  end

  def new
    @group  = current_user.groups.where(id: params[:group_id]).first
    if @group
      @group_transaction = @group.group_transactions.new
      @members = @group.group_members
    else
      redirect_to groups_path
    end
  end

  def create
    @group  = current_user.groups.where(id: params[:group_id]).first
    
    if @group
      @group_transaction = @group.group_transactions.new(create_params.merge({user_id: current_user.id}))
      if @group_transaction.save 
        unless @group_transaction.all_group 
          @group_transaction.add_members(params[:members]) if params[:members].present?
        end
        redirect_to "/groups/#{@group.id}"
      else
        render :new
      end
    else
      redirect_to groups_path
    end
  end
  
  private 
  
  def create_params
    params.require(:group_transaction).permit(:amount, :reason, :all_group)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @groups = current_user.groups
  end

  def show
    @group  = current_user.groups.where(id: params[:id]).first
    last_audit = @group.group_audits.last
    @transactions = @group.group_transactions
    if last_audit.present?
      @transactions = @transactions.where("created_at > ?", last_audit.created_at)
    end

  end
  
  def  new
    @group  = current_user.groups.new
  end
  
  def create
    @group  = current_user.groups.new(create_params)
    if @group.save
      
      redirect_to "/groups/#{@group.id}"
    else
      render :new
    end
  end

  def members
    @group  = current_user.groups.where(id: params[:id]).last
    if @group
      @users = User.where("id not in (?)", @group.group_members.map(&:user_id) << 0)
    else 
      redirect_to groups_path
    end
  end
  
  def add_members
    @group  = current_user.groups.where(id: params[:id]).last
    if @group
      if params[:group_member].present?
        @group.add_members(params[:group_member].values.map(&:to_i))
      end
      
      #@users = User.where("id not in (?)", @group.group_members.map(&:user_id))
      redirect_to "/groups/#{@group.id}"
    else 
      redirect_to groups_path
    end
  end

  def make_audit
    @group  = current_user.groups.where(id: params[:id]).last
    if @group
      @group.make_audit(current_user.id)
      redirect_to "/groups/#{@group.id}"
    else 
      redirect_to groups_path
    end
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end
  
  private
  
  def create_params
    params.require(:group).permit(:name, :reason)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_audits_helper.rb
module GroupAuditsHelper
end

app/helpers/group_transactions_helper.rb
module GroupTransactionsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/group_audits/index.html.erb
<div class="wrapper row2">
  <div id="container" class="clear"> 
    <!-- ####################################################################################################### -->
    <div id="content">
      <h1>Audits for <%= @group.name %></h1>
      <table>
	<thead>
	  <td>
	    Date
	  </td>
	  <td>
	    User
	  </td>
	  <td>
	    Action
	  </td>
	</thead>
	<%- @group_audits.each do |ga| %>
	<tr>
	  <td>
	    <%= ga.created_at %>
	  </td>
	  <td>
	    <%= ga.user.name %>
	  </td>
	  <td>
	    <a href="/groups/<%= ga.group_id %>/group_audits/<%= ga.id %>">Action</a>
	  </td>
	</tr>
	<%- end %>
      </table>
    </div>
  </div>
</div>

app/views/group_audits/show.html.erb
<div class="wrapper row2">
  <div id="container" class="clear"> 
    <!-- ####################################################################################################### -->
    <div id="content">
      <h1>Audits for <%= @group.name %> at <%= @group_audit.created_at %></h1>
      <table>
	<thead>
	  <td>
	    Email
	  </td>
	  <td>
	    Amount
	  </td>
	</thead>
	<%- @users.each do |user| %>
        <tr>
	   <td>
	     <%= user.first[0] %>
	   </td>
	   <td>
	     <%= user.first[1] %>
	   </td>
	 </tr>
	<%- end %>
      </table>
      <h1>Transactions</h1>
      <table>
	  <tr>
	    <th>
	      Amount
	    </th>
	    <th>
	      Reason
	    </th>
	    <th>
	      Paid by
	    </th>
	    
	    <th>All Group</th>
	    <th>Number of members</th>
	    <th>
	      Date
	    </th>
	      
	  </tr>
	  <%- @transaction.each do |trn| %>
	  <tr>
	    <td>
	      <%= trn.amount %>
	    </td>
	    <td><%= trn.reason %></td>
	    <td><%= trn.user.name %></td>
	    <td><%= trn.all_group %></td>
	    <td><%= trn.all_group ? 'All Group' : trn.group_transaction_members_count %></td>
	    <td><%= trn.created_at %></td>
	  </tr>
	  <%- end %>
	</table>
    </div>
  </div>
</div>

app/views/group_transactions/new.html.erb
<div class="wrapper row2">
  <div id="container" class="clear"> 
    <!-- ####################################################################################################### -->
    <div id="content">
      <h1>New Group Transaction</h1>
      
      <%= form_for @group_transaction, url: {action: "create"} do |f| %>
      <%= f.hidden_field(:members) %>
      <p>
	<strong class="one_quarter">Name</strong>
	<%= f.text_field :amount %>
      </p>
      <p>
	<strong class="one_quarter">Reason</strong>
	<%= f.text_field :reason %>
      </p>
      <p>
	<strong class="one_quarter">All group</strong>
	<%= f.check_box :all_group , onclick: "showMembers();" %>
      </p>
      <div class="hide" id="transactionMembers">
	<h2>Members</h2>
	<%- @members.each do |member|%>
	<p><input class="pointer" type="checkbox" id="puppy_gooddog" name="members[<%= member.id%>]" value="<%= member.user_id %>" />&nbsp;&nbsp;<%= member.user.name %></p>
	<%- end %>
      </div>
      <p>
	<%= f.submit "Create" %>
	<a href="/groups/<%= @group.id %>"class="btn btn primary"> Cancel</a>
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="wrapper row5">
  <div id="pageintro" class="clear">
    <p class="pageheader">Groups <small><a href="<%= new_group_path %>" style="font-size:14px;">New Group</a></small></p>
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper row2">
  <div id="container" class="clear"> 
    <!-- ####################################################################################################### -->
    <div id="portfolio">
      <ul class="clear">
	<%- @groups.each do |group| %>
        <li><a href="/groups/<%= group.id %>"><img src="../images/demo/300x280.gif" alt="" /></a>
          <p class="project_name"><%= group.name%></p>
          <p><%= group.reason %></p>
        </li>
	<%- end %>
	<%- if @groups.size == 0%>
	<h1 class="red_group">Please Create Your Group and add Member</h1>
	<a href="<%= new_group_path %>" style="font-size:14px;">New Group</a>
	<%- end %>
        
      </ul>
    </div>
  </div>
</div>

app/views/groups/members.html.erb
<div class="wrapper row2">
  <div id="container" class="clear"> 
    <!-- ####################################################################################################### -->
    <div id="content">
      <h1>Add member into <%= @group.name %></h1>
      <%= form_tag("/groups/#{@group.id}/add_members") do %>
      <table>
	<thead>
	  <tr>
	    <td>
	      Select
	    </td>
	    <td>
	      Name
	    </td>
	    <td>
	      Mobile
	    </td>
	  </tr>
	  <%- @users.each do |user| %>
	  <tr>
	    <td>
	      <input class="pointer" type="checkbox" name="group_member[<%= user.id %>]" value="<%= user.id %>">
	    </td>
	    <td>
	      <%= user.name %>
	    </td>
	    <td>
	      <%= user.mobile %>
	    </td>
	  </tr>
	  <%- end %>
	</thead>
      </table>
      <%= submit_tag "Save" %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="wrapper row2">
  <div id="container" class="clear"> 
    <!-- ####################################################################################################### -->
    <div id="content">
      <h1>New Group</h1>
      
      <%= form_for @group, url: {action: "create"} do |f| %>
      <% if @group.errors.any? %>
      <ul>
	<% @group.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
      </ul>
      <% end %>
      <p>
	<strong class="one_quarter">Name</strong>
	<%= f.text_field :name %>
      </p>
      <p>
	<strong class="one_quarter">Reason</strong>
	<%= f.text_field :reason %>
      </p>
      <p>
	<%= f.submit "Create" %>
	<a href="/groups" class="btn btn-primary">Cancel</a>
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="wrapper row2">
  <div id="container" class="clear"> 
    <!-- ####################################################################################################### -->
    <div id="content">
      <%- if @transactions.count > 0 %>
      <a style="float:right;font-size:20px;" href="/groups/<%= @group.id %>/make_audit">
	Make audit
      </a>
      <%- end %>
      &nbsp;&nbsp;&nbsp;&nbsp;
      
      <a style="float:right;font-size:20px;margin-right:20px;" href="/groups/<%= @group.id %>/group_audits">
	Audits Reports
      </a>

      
      <h1><%= @group.name %> Group</h1>

      <div>
	<h2>Members<small style="padding-left:20px;"><a href="/groups/<%= @group.id %>/members">Add Member</a></small></h2>
	<ul>
	  <%- @group.group_members.each do |member|%>
	  
	  <li>
	    <%= member.user.name %>
	    <strong>(<%= member.balance %> Balance)</strong>
	  </li>
	  <%- end %>
	</ul>
      </div>
      <div>
	<h2>Transactions<small style="padding-left:20px;"><a href="<%= new_group_group_transaction_path(@group)%>">New Transaction</a></small></h2>
	<table>
	  <tr>
	    <th>
	      Amount
	    </th>
	    <th>
	      Reason
	    </th>
	    <th>
	      Paid by
	    </th>
	    <th>
	      Date
	    </th>
	  </tr>
	  <%- @transactions.each do |trn| %>
	  <tr>
	    <td>
	      <%= trn.amount %>
	    </td>
	    <td><%= trn.reason %></td>
	    <td><%= trn.user.name %></td>
	    <td><%= trn.created_at %></td>
	  </tr>
	  <%- end %>
	</table>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="wrapper row5">
  <div id="pageintro">
    <h1>XXXXXXXXXXXX</h1>
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper row2">
  <div id="container" class="clear"> 
    <!-- ####################################################################################################### -->
    <div id="homepage"> 
      <!-- ###### -->
      <div id="shout">
        <p>&ldquo; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc non diam erat. In fringilla massa ut nisi ullamcorper pellentesque &bdquo;</p>
      </div>
      <!-- ###### -->
      <div id="latest" class="clear">
        <div class="two_quarter">
          <h2>Lorem ipsum dolor sit amet consectetur</h2>
          <img class="imgl" src="images/demo/185x185.gif" alt="" />
          <p>This is a W3C standards compliant free website template from <a href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a>. For full terms of use of this template please read our <a href="http://www.os-templates.com/template-terms">Website Template Licence</a>.</p>
          <p>You can use and modify the template for both personal and commercial use. You must keep all copyright information and credit links in the template and associated files. For more CSS templates visit <a href="http://www.os-templates.com/">Free Website Templates</a></p>
          <p class="more"><a href="#">Read More &raquo;</a></p>
        </div>
        <div class="two_quarter lastbox">
          <h2>Lorem ipsum dolor sit amet consectetur</h2>
          <img class="imgl" src="images/demo/185x185.gif" alt="" />
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc non diam erat. In fringilla massa ut nisi ullamcorper pellentesque. Quisque non luctus sem. Nullam non magna vel nisi posuere bibendum vitae sed dui. Nulla at lorem tortor, non rhoncus odio. Nunc sit amet interdum orci. Nam at mauris ut arcu fringilla facilisis. Donec tempus massa vitae nunc pulvinar sed lobortis leo rutrum.</p>
          <p class="more"><a href="#">Read More &raquo;</a></p>
        </div>
      </div>
      <!-- ###### --> 
    </div>
    <!-- ####################################################################################################### --> 
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="wrapper row3">
</div>
<!-- ####################################################################################################### -->
<div class="wrapper row4">
  <div id="copyright" class="clear">
    <p class="fl_left">Copyright &copy; 2014 - All Rights Reserved - <a href="#">Domain Name</a></p>
    <p class="fl_right">Template by <a target="_blank" href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="wrapper row1">
  <div id="header" class="clear">
    <div class="fl_left">
      <h1><a href="<%= current_user ? groups_path : '/' %>">Business Plan</a></h1>
      <p>Free Website Template</p>
    </div>
    <ul id="topnav">
      <li class="active"><a href="/">Home</a></li>
      <li ><a href="<%= groups_path %>">My Groups</a></li>
      <%- unless current_user  %><li ><%= link_to 'Sign in', new_user_session_path %></li>
      <%- else %>
      <li ><%= link_to "Sign out #{current_user.name}", destroy_user_session_path, :method => :delete %></li>
      <%- end %>
    </ul>
  </div>
</div>
<!-- ####################################################################################################### -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Billapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="top">
  <%= render :partial => "layouts/header.html.erb" %>
  
  <%= yield %>
  <%= render :partial => "layouts/footer.html.erb" %>

</body>
</html>